
- name: Setup Postgresql with web interface
  hosts: all

  roles:

    - role: geerlingguy.postgresql
      tags: postgresql
    - role: geerlingguy.apache
      tags: apache
    - role: geerlingguy.php
      tags: php
    - role: local.adminer
      tags: adminer
